### ISSUE TITLE
ReferenceError: self is not defined

### ISSUE THREAD

**Issue by guatedude2** [Asweallcan/react-flex-dnd#5]
Hi,This library is exactly what I'm looking for. However, I'm not able to get past this error:

```
/test-project/node_modules/react-flex-dnd/dist/index.js:3
}(self, (e, t) => (() => {
  ^
ReferenceError: self is not defined
    at ../../node_modules/react-flex-dnd/dist/index.js (/test-project/node_modules/react-flex-dnd/dist/index.js:3:3)
    at /test-project/build/index.js:7:50
    at Object.<anonymous> (/test-project/app/pages/DashboardPage.tsx:5:63)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Function.Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at Object.<anonymous> (/test-project/node_modules/@remix-run/serve/dist/cli.js:38:13)
```

Any ideas why this is happening?

**Comment by guatedude2** [comment]
Looks like its related to UMD modules and I'm using CommonJS. Once I checked out and built it and changing the tsconfig.json output.library.type = "commonjs",

**Comment by Asweallcan** [comment]
is there any other problems?
